#ifndef KEM_H
#define KEM_H
#include "params.h"
#include <stdint.h>

#define PQCLEAN_KYBER768_CLEAN_CRYPTO_SECRETKEYBYTES  KYBER_SECRETKEYBYTES
#define PQCLEAN_KYBER768_CLEAN_CRYPTO_PUBLICKEYBYTES  KYBER_PUBLICKEYBYTES
#define PQCLEAN_KYBER768_CLEAN_CRYPTO_CIPHERTEXTBYTES KYBER_CIPHERTEXTBYTES
#define PQCLEAN_KYBER768_CLEAN_CRYPTO_BYTES           KYBER_SSBYTES

#define PQCLEAN_KYBER768_CLEAN_CRYPTO_ALGNAME "Kyber768"

int PQCLEAN_KYBER768_CLEAN_crypto_kem_keypair(uint8_t *pk, uint8_t *sk);;

#endif
